### ISSUE TITLE
Prepare content for widgets

### ISSUE THREAD

**Issue by fgassert** [PReP-Team/prep-prototype#10]

**Comment by fgassert** [comment]
For each widget, we should prepare:
 - chart type / map type
 - data source (end point or file)
 - visualization parameters (variables etc.) if necessary
 - title
 - pop-out description
 - citation info
 - link to authoritative data source

**Comment by cbweinstein** [comment]
Hi all, see below example of a widget pulled from NCA Region: Chapter 18 Midwest, Fig. 18.2:

**Chart type / map type**: Map
**Data source (end point or file)**:
	**Data**: ftp://filsrv.cicsnc.org/tsu/nca3-data/Figure_18-6_files.tar.gz
        **Metadata**: http://catalog.data.gov/dataset/eighth-degree-conus-daily-downscaled-climate-projections-by-katharine-hayhoe
			
**Visualization parameters**: Each figure can be a separate widget (4 total)
**Title**:
	**Top Left**: Projected Mid-Century Temperature Changes in the Midwest: Average Temperature
	**Top Right**: Projected Mid-Century Temperature Changes in the Midwest: Days above 95°F
	**Bottom Left**: Projected Mid-Century Temperature Changes in the Midwest: Frost-Free Season
	**Bottom Right**: Projected Mid-Century Temperature Changes in the Midwest: Cooling Degree Days
**Pop-out description**:
Projected increase in annual average temperatures by mid-century (2041-2070) as compared to the 1971-2000 period tell only part of the climate change story. Maps also show annual projected increases in the number of the hottest days (days over 95°F), longer frost-free seasons, and an increase in cooling degree days, defined as the number of degrees that a day’s average temperature is above 65°F, which generally leads to an increase in energy use for air conditioning. Projections are from global climate models that assume emissions of heat-trapping gases continue to rise (A2 scenario). (Figure source: NOAA NCDC / CICS-NC).
**Citation info**: Figure source: NOAA NCDC / CICS-NC
**Link to authoritative data source**:
https://data.globalchange.gov/report/nca3/chapter/midwest/figure/projected-midcentury-temperature-changes-in-the-midwest

**Comment by fgassert** [comment]
Hi @apfister,
Let me know if this is the type of info you are looking for, and we can expand for the other widgets. Also, if there is a better format to deliver this if you plan on parameterizing widgets.

**Comment by apfister** [comment]
@fgassert @cbweinstein this is exactly what i was looking for. thanks!

**Comment by apfister** [comment]
@fgassert @cbweinstein 

the data downloaded from the FTP link does not appear to match up directly with the data in the Figures @ https://data.globalchange.gov/report/nca3/chapter/midwest/figure/projected-midcentury-temperature-changes-in-the-midwest.

At this point, I will just publish the data from the FTP site as a service to use in the widget. We can always swap out data sources and make adjustments to color ramps as needed.

**Comment by fgassert** [comment]
Hmm sorry @apfister, I don't have ArcMap on my mac so wasn't able to take a look. I suspect several of these datasets will have this issue, and will see if I can get some support from the data team (unless you also have some analyst time available). Lets try to proceed as far as possible with what we have for now though.

Also, could you send me the end point you stand up?

**Comment by apfister** [comment]
@fgassert very rough draft now @ http://apfister.github.io/prep-prototype/#/indicators-test

**Comment by cbweinstein** [comment]
Hi @apfister, could you take a look at these as well?
[PREP Foundational Datasets.docx](https://github.com/PReP-Team/prep-prototype/files/199772/PREP.Foundational.Datasets.docx)
