### ISSUE TITLE
Create data/map page

### ISSUE THREAD

**Issue by fgassert** [PReP-Team/prep-prototype#18]
We need a place where people can simply explore datasets and download them. 
![slice 1](https://cloud.githubusercontent.com/assets/2185984/14369546/fd1a4700-fcf3-11e5-89e3-fbf539407985.png)

Following the attached mock up, please build a map / data exploration page.
The page should:
 - [x] be full screen, and need not be responsive
 - [x] have a minimal header and no footer
 - [x] list all available datasets on the left hand side that the user can toggle on and off (the search need not function)
 - [x] have a pop-up attached to each dataset with additional details about the dataset and download info.
 - [x] focus on the map view of the data
 - [x] have a minimal legend (this will likely be the most difficult part)

@sergioestella apologies in advance for butchering your designs

Thanks!

**Comment by sergioestella** [comment]
We've already started working on it. I'll let you know as soon as we have
something to share with you.

Thanks,
Sergio

On 7 April 2016 at 19:07, Francis Gassert <notifications@github.com> wrote:

> We need a place where people can simply explore datasets and download
> them.
> [image: slice 1]
> <https://cloud.githubusercontent.com/assets/2185984/14369546/fd1a4700-fcf3-11e5-89e3-fbf539407985.png>
>
> Following the attached mock up, please build a map / data exploration page.
> The page should:
>
>    - be full screen, and need not be responsive
>    - have a minimal header and no footer
>    - list all available datasets on the left hand side that the user can
>    toggle on and off (the search need not function)
>    - have a pop-up attached to each dataset with additional details about
>    the dataset and download info.
>    - focus on the map view of the data
>    - have a minimal legend (this will likely be the most difficult part)
>
> @sergioestella <https://github.com/sergioestella> apologies in advance
> for butchering your designs
>
> Thanks!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/PReP-Team/prep-prototype/issues/18>
>



-- 
-- 
*Vizzuality*
C/. Eloy Gonzalo, 27 2º - 6 & 7
28010 MADRID / SPAIN
M. +34 669 707 101 / T. +34 914 478 732
skype: sergioestella
www.vizzuality.com

**Comment by fgassert** [comment]
@sergioestella please post your designs here when ready.

The only thing I noticed this morning was that citation/provenance for datasets will be important to show.

**Comment by sergioestella** [comment]
![prep_data_01](https://cloud.githubusercontent.com/assets/7260948/14469673/2d1d19c8-00e6-11e6-9f33-a9c276d29414.png)
![prep_data_02](https://cloud.githubusercontent.com/assets/7260948/14469674/2d1ef914-00e6-11e6-92fb-30746ce59492.png)
![prep_data_03](https://cloud.githubusercontent.com/assets/7260948/14469672/2d1c85a8-00e6-11e6-812c-6fb405132987.png)
![prep_data_04](https://cloud.githubusercontent.com/assets/7260948/14469675/2d20364e-00e6-11e6-9756-5838e6cadbcd.png)

**Comment by apfister** [comment]
@fgassert @sergioestella 
i've started work on this, among other things, and you can see the progress @ http://prep-team.github.io/prep-prototype/data

**Comment by sergioestella** [comment]
Thanks @apfister do I need a password?

**Comment by apfister** [comment]
@sergioestella emailed it to you. let me know if you did not receive it.

**Comment by apfister** [comment]
just updated with a legend view and a first pass at a popup for showing data info. the popup just shows static data for now but will eventually be dynamic.
