### ISSUE TITLE
Update PREP logo: Partnership for Resilience and Preparedness

### ISSUE THREAD

**Issue by fgassert** [PReP-Team/prep-prototype#28]
We've decided to stick with "Partnership for Resilience and Preparedness" as the name. Can you update the logo to reflect? Emphasis on "Resilience and Preparedness".

**Comment by fgassert** [comment]
Hey @sergioestella,
Could you take care of this quickly early next week?
Thanks!

**Comment by sergioestella** [comment]
Hi Francis,
here is the logo with the amendments. Let me know if everything is ok.
thanks

[logo-prep-v2.zip](https://github.com/PReP-Team/prep-prototype/files/290965/logo-prep-v2.zip)

**Comment by fgassert** [comment]
Excellent thanks!
