### ISSUE TITLE
Explore creating dashboard widgets with branding

### ISSUE THREAD

**Issue by fgassert** [PReP-Team/prep-prototype#3]
Hi @apfister,
Could you explore creating a few dashboard widgets following the branding from style 1 in the attached?
Thanks!

[PREP_Stylespresentation.pdf](https://github.com/PReP-Team/prep-prototype/files/165867/PREP_Stylespresentation.pdf)

**Comment by fgassert** [comment]
You can commit directly to this branch https://github.com/PReP-Team/prep-prototype/tree/explore-dashboards

**Comment by fgassert** [comment]
Hey @apfister,
Would be great to see what you've drafted so far if you can sync your progress.

**Comment by apfister** [comment]
@fgassert there isn't much there but i will look to push later this afternoon.

**Comment by apfister** [comment]
can we close/combine with #10 ?

**Comment by fgassert** [comment]
Looking good. Let's keep this thread separate from the data preparation one. 

I think we want to add a few additional things to each card to give them more context.

@sergioestella please weight in but generally:
- Title
- Topic tags?
- Pop-up description with
- Citation/bi-line
- Link to dataset page and/or data download?

Sound good?

**Comment by sergioestella** [comment]
@fgassert alright, I'll move this forward and let you know when ready.

**Comment by fgassert** [comment]
See issue #20 re dataset detail pop-ups.
