### ISSUE TITLE
Select more international home page photos

### ISSUE THREAD

**Issue by fgassert** [PReP-Team/prep-prototype#32]
Would it be possible to use the photography on the home page to imply a more international focus for PREP? 

We can switch out the NYC for Porto Alegre if we end up working with them. In the mean time, Amy would like to replace some of the images to help show that we have a international focus. Hope, vulnerability, and locality seem to be themes in the photos you've used so far that are working well.

meh. https://www.flickr.com/photos/mbcj/6112239889/in/photolist-pPM1Ac-w9JZGc-9ejrn3-ecipXZ-5dDoKc-raTj4w-fZjuaR-3LkK9Y-qHRtGR-dV9fsh-qcEAt2-heMVkp-5JAMNw-niLpDc-nA2awJ-niLiGK-nzY2iV-4wdyLn-veJSJV-4ubmQV-5CNjwk-abTtZz-6pZT59-aytuHn-7TewmB-nujQcb-keJ6rk-4AaWnc-bmsRbW-dZXzDK-pC6EWP-u8Xr-9vUkvv-dgfV8b-eaTU3o-ieaLpz-5XHRM6-jje2wn-a1isB6-DRkaox-4UMDNA-7cSCsX-aj7PYn-83tLgn-5hvZsp-4wEhrJ-rNzs-dPjhnB-iPQzUc-g9KQyK

better? https://www.flickr.com/photos/fotografolucas/16520779132/in/photolist-pPM1Ac-w9JZGc-9ejrn3-ecipXZ-5dDoKc-raTj4w-fZjuaR-3LkK9Y-qHRtGR-dV9fsh-qcEAt2-heMVkp-5JAMNw-niLpDc-nA2awJ-niLiGK-nzY2iV-4wdyLn-veJSJV-4ubmQV-5CNjwk-abTtZz-6pZT59-aytuHn-7TewmB-nujQcb-keJ6rk-4AaWnc-bmsRbW-dZXzDK-pC6EWP-u8Xr-9vUkvv-dgfV8b-eaTU3o-ieaLpz-5XHRM6-jje2wn-a1isB6-DRkaox-4UMDNA-7cSCsX-aj7PYn-83tLgn-5hvZsp-4wEhrJ-rNzs-dPjhnB-iPQzUc-g9KQyK/

**Comment by danielcasius** [comment]
Hi Francis.
I found a quite good landscape of Porto Alegre that could fit replacing the NYC photo: https://flic.kr/p/t2nAcY

For the rest of photos, it's hard to find good ones with the proper license (avoiding all rights reserved ones) if we are only focused on that place.
I found some interesting photos of farmers from india and brazil:
https://commons.wikimedia.org/wiki/File:Traditional_dress,_faces,_scenery_of_Himachal_Pradesh_India.jpg
https://en.wikipedia.org/wiki/Agriculture_in_Brazil#/media/File:Abr_horta_Antonio_Cruz.jpg
In the same line, but from a more technical point of view, could be this one: https://flic.kr/p/a1rsZ2
CIAT (International Center for Tropical Agriculture) have some amazing albums that could be very useful:
https://www.flickr.com/photos/ciat/albums

Let me know your thoughts about this approach.

**Comment by fgassert** [comment]
Sounds good. They don't all have to be for the one city. 
We just want to avoid falling into the "western NGO photos of poor african women and children". The [woman farming](https://en.wikipedia.org/wiki/Agriculture_in_Brazil#/media/File:Abr_horta_Antonio_Cruz.jpg) is better than [woman in traditional dress](https://commons.wikimedia.org/wiki/File:Traditional_dress,_faces,_scenery_of_Himachal_Pradesh_India.jpg)

The Porto Alegre landscape is perfect.
