### ISSUE TITLE
Draft content for about, partners, faqs

### ISSUE THREAD

**Issue by fgassert** [PReP-Team/prep-prototype#33]
Hi @cbweinstein,
Can you prepare some draft content for the about page, partners, and FAQs pages. Please work off what we currently have in the prototype and the partnership materials in the basecamp.

http://prep-team.github.io/prep-prototype/#/about
https://3.basecamp.com/3258807/buckets/438588/vaults/62246855

Todo:
- [ ] Review about text
- [ ] Propose partner page intro text
- [x] Upload partner logos
- [ ] Propose FAQ text

**Comment by cbweinstein** [comment]
Hi @fgassert,

Please see attached partner logos. The only logo I had trouble finding was Earth Knowledge's; I wasn't able to pull directly from their website.

More content to come.

![10205437-earth-knowledge-logo](https://cloud.githubusercontent.com/assets/16316283/14926587/df0c9028-0e1a-11e6-8a54-b228aa96fcb4.jpg)
![cartodb](https://cloud.githubusercontent.com/assets/16316283/14926586/df0a20b8-0e1a-11e6-9f5d-26fae63db410.png)

![descartes_logo](https://cloud.githubusercontent.com/assets/16316283/14926588/df0c82b8-0e1a-11e6-8d01-9138f4855663.png)
![doi_logo](https://cloud.githubusercontent.com/assets/16316283/14926585/df09aee4-0e1a-11e6-92e9-f4630c679b42.png)


![esri-10globelogo_srgbflat](https://cloud.githubusercontent.com/assets/16316283/14926589/df11ca8e-0e1a-11e6-96ef-5cc12bbfbe0d.jpg)

![nasa_logo svg](https://cloud.githubusercontent.com/assets/16316283/14926591/df14c572-0e1a-11e6-8c98-25adda70713a.png)
![noaa_logo](https://cloud.githubusercontent.com/assets/16316283/14926590/df1341b6-0e1a-11e6-913c-248270379b93.png)

![partner-vizzuality-logo](https://cloud.githubusercontent.com/assets/16316283/14926592/df1648b6-0e1a-11e6-8b12-2864710e4481.png)
![usgcrp-logo-72dpi-dark-blue-letters](https://cloud.githubusercontent.com/assets/16316283/14926593/df17521a-0e1a-11e6-963a-2251010518f0.jpg)
![wri_logo_4c](https://cloud.githubusercontent.com/assets/16316283/14926594/df19f59c-0e1a-11e6-9d50-d6780ee022f6.JPG)
