### ISSUE TITLE
Explore site structure based off wireframes

### ISSUE THREAD

**Issue by fgassert** [PReP-Team/prep-prototype#4]
Hi @apfister,
Could you chat with @ajturner to propose options for site structure following the wireframes here:
https://projects.invisionapp.com/share/UZ5Y0BX34#/screens/133742633

Please propose a couple options with pro/con of each.

Generally we have:

```
Home
--Dashboards
----Specific dashboard [indicators|insights|tools]
--Insights
----Specific insight (custom content)
--Data
----Map view
----Data detail page
--Ancillary pages
----About
----Partnerships
----... etc.
```

**Comment by apfister** [comment]
@fgassert @ajturner 

We plan on working with an EmberCLI app for the prototype. Just want to make sure it's ok if I push that app to this Repo to start addressing these issues. Can you please confirm?

**Comment by fgassert** [comment]
Sounds good thanks!

**Comment by apfister** [comment]
@fgassert, @ajturner  i've started working on my own fork so take a look here, http://apfister.github.io/prep-prototype/. it's definitely a rough start, but we can use that as a starting point. please loop in David as i don't see his GH user on here to tag him.

**Comment by ajturner** [comment]
@d4weed for awareness

**Comment by fgassert** [comment]
Thanks @apfister, this is a great first pass.
Could you create a PR to work out of the local repo?
If you don't mind, I'd like to have Vizzuality take a crack at the homepage. Let us know if there's any way you prefer to have them work on it.

In the mean time if you could focus on #3 that would be great!
Let me know if you want to connect briefly on Skype.

**Comment by apfister** [comment]
@fgassert 

>Could you create a PR to work out of the local repo?

I have a fork of the repo that I was planning on submitting PR's from. Will that work? Sorry, I'm still a bit new to all the GH ins & outs. Just let me know what works best for everyone and I'll do that.

>If you don't mind, I'd like to have Vizzuality take a crack at the homepage. Let us know if there's any way you prefer to have them work on it.

Totally down for that. @d4weed & anyone else comfortable with working with the Ember app? The only reason I put a little extra work into what you see now is to just get started while you were all having fun out in Palm Springs :) The designs were beautiful and I got excited in wanting to see them come to life. 

I also wanted to test out the Site Layout you have mentioned in the first post.

I'll shift my attention to #3 for the time being.

**Comment by fgassert** [comment]
No worries. A fork and a branch are essentially the same thing, its just easier to track branches together, and fetch/clone the whole tree. Let me pull your fork in -- then you can clone and branch from here.
