### ISSUE TITLE
Prepare Sonoma feature services for charts

### ISSUE THREAD

**Issue by fgassert** [PReP-Team/prep-prototype#42]
Hi @csavoldelli,
Could you take a look at these excel files and stand them up as AGOL feature services that can be queried for charts. You will need to convert them to properly formatted csvs first.
https://drive.google.com/drive/folders/0B8ABwKwEEQP6MWs5S29JaVlNYkk

Several of these have multiple models. Please prepare a column for the ensemble mean as well as for each model.

- [ ] ~~Three day heat waves - over 95 deg and 100 deg~~
- [x] Historical and projected annual rainfall
- [x] Three day high flow events - Lower Russian River

Once you've uploaded them on ArcGIS online, please post the endpoints here.

**Comment by csavoldelli** [comment]
[Historical and projected annual rainfall](http://worldresources.maps.arcgis.com/home/item.html?id=3e152f79a83b48afb2fb603b13cc341f)
[Three day high flow events](http://worldresources.maps.arcgis.com/home/item.html?id=15e51a8d05c741008363f5a321734898)

Let me know if there are any issues accessing/using these.
