### ISSUE TITLE
Create widgets with real data

### ISSUE THREAD

**Issue by fgassert** [PReP-Team/prep-prototype#5]
For each of the charts in here: [NCA_Figures_ClimateProjections.docx](https://github.com/PReP-Team/prep-prototype/files/165924/NCA_Figures_ClimateProjections.docx) please attempt to recreate the map or graph as a widget.

This should help us identify:
 - Is current hosting sufficient for visualizations?
 - What level of data processing should we expect?
 - What sort of metadata should we surface on the front end to maximize usability?

**Comment by fgassert** [comment]
Hey @apfister,
Have you had a chance to look at this doc and see if you can extract the data? Let me know if you want me to have someone do additional data prep or extract specific summary info.
Thanks!
F

**Comment by apfister** [comment]
can we close/combine this with #10 ?

**Comment by fgassert** [comment]
Yep. Thanks
