### ISSUE TITLE
Build prototype homepage

### ISSUE THREAD

**Issue by fgassert** [PReP-Team/prep-prototype#9]
Hi @d4weed, @sergioestella,
Could you guys try building the homepage for the PREP prototype?

If you can work within the ember+bootstrap framework, the homepage template and data model are here:
https://github.com/PReP-Team/prep-prototype/tree/develop/app/home
And header here:
https://github.com/PReP-Team/prep-prototype/tree/develop/app/templates/partials

Let me know if you have q's

**Comment by d4weed** [comment]
Yeah, not sure we'll need to link it to ember, maybe just the html structure, but I leave that to @davidsingal

**Comment by d4weed** [comment]
btw @fgassert can you invite @clementprdhomme to the project?

**Comment by davidsingal** [comment]
I agree with @d4weed, for the homepage we don't need add ember. But we are working with bootstrap for the html structure and styles. Anyway we will consider this to be ember friendly.

**Comment by fgassert** [comment]
Great, looking forward to seeing what you build!

**Comment by davidsingal** [comment]
Here we've published the homepage: http://vizzuality.github.io/ppp-homepage/, and this is the repo with source files: https://github.com/Vizzuality/ppp-homepage.

We are trying to follow the bootstrap conventions and the way to make override in their modules. We've use POSTCSS to make css (is very similar to sass or less), in dist folder you can found the compiled css file. We've focused in html structure and we think it's easy make modules for ember with that.

**Comment by fgassert** [comment]
Excellent. This looks great.

@apfister could you take a look at this and think about how best to pull the two together, keeping in mind that we will want to make changes to the home page eventually. Also, please let the team know if there are things that will make further integration easier.

**Comment by d4weed** [comment]
One thing @davidsingal didn't mention is that this homepage has also the responsive rules built in, so you can also use it as a guide for that.

While I'm not sure we will be having a fully responsive site for the alpha, we think at least the homepage should be viewable in mobile phones.

Let us know if there's any doubts regarding this or anything else

**Comment by apfister** [comment]
home page updated here :: http://apfister.github.io/prep-prototype/

**Comment by fgassert** [comment]
Excellent
